#!/bin/sh -e
# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.

if [ -z "$VIRTUAL_ENV" -a -d venv/ ]; then
    . venv/bin/activate
fi

if [ -z "$PYTHONPATH" ]; then
    export PYTHONPATH=src
else
    export PYTHONPATH="src:$PYTHONPATH"
fi

flake8 || exit $?
black -l 79 --diff --check src tests || exit $?
# python3 -m unittest -v "$@"
coverage run -m unittest -v "$@"
