name: Sync docs from Discourse

on:
  workflow_dispatch:
  schedule:
    - cron: '53 0 * * *' # Daily at 00:53 UTC

jobs:

  sync-docs:
    name: Open PR with docs changes
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Publish documentation
        uses: canonical/upload-charm-docs@main

        id: publishDocumentation
        with:
          discourse_host: discourse.charmhub.io
          discourse_api_username: ${{ secrets.DISCOURSE_API_USERNAME }}
          discourse_api_key: ${{ secrets.DISCOURSE_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: "true"

      - name: Show migrate output
        run: echo '${{ steps.publishDocumentation.outputs.migrate }}'
      - name: Show reconcile output
        run: echo '${{ steps.publishDocumentation.outputs.reconcile }}'

